// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3V3klxXJ6b5NF1bydvYW0RVSJvDOY0SM',
    appId: '1:673328386983:web:ff579cd9ae09a395349c82',
    messagingSenderId: '673328386983',
    projectId: 'nail-tech-daily-notes',
    authDomain: 'nail-tech-daily-notes.firebaseapp.com',
    storageBucket: 'nail-tech-daily-notes.firebasestorage.app',
    measurementId: 'G-02E7HMR1F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0cjHklmqp7UrHJCiu4_F3NqZpecik_0Y',
    appId: '1:673328386983:android:7ac644eaff615e17349c82',
    messagingSenderId: '673328386983',
    projectId: 'nail-tech-daily-notes',
    storageBucket: 'nail-tech-daily-notes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfzUoFTobI2hvQ-ClMqHSL2MXcV9lyisM',
    appId: '1:673328386983:ios:ee90732b7ef0ce5f349c82',
    messagingSenderId: '673328386983',
    projectId: 'nail-tech-daily-notes',
    storageBucket: 'nail-tech-daily-notes.firebasestorage.app',
    iosBundleId: 'com.sokkhorn.nailTechDailyNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfzUoFTobI2hvQ-ClMqHSL2MXcV9lyisM',
    appId: '1:673328386983:ios:ee90732b7ef0ce5f349c82',
    messagingSenderId: '673328386983',
    projectId: 'nail-tech-daily-notes',
    storageBucket: 'nail-tech-daily-notes.firebasestorage.app',
    iosBundleId: 'com.sokkhorn.nailTechDailyNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3V3klxXJ6b5NF1bydvYW0RVSJvDOY0SM',
    appId: '1:673328386983:web:9b9781f7505aab3f349c82',
    messagingSenderId: '673328386983',
    projectId: 'nail-tech-daily-notes',
    authDomain: 'nail-tech-daily-notes.firebaseapp.com',
    storageBucket: 'nail-tech-daily-notes.firebasestorage.app',
    measurementId: 'G-6X8XEG66QP',
  );
}
